"""
Django settings for gogo project.

Generated by 'django-admin startproject' using Django 5.2.7.

Documentation:
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path
import os
import cloudinary
import cloudinary.uploader
import cloudinary.api
from dotenv import load_dotenv

# ----------------------------------------
# 📂 تحميل ملف البيئة .env
# ----------------------------------------
load_dotenv()

# ----------------------------------------
# 📂 المسار الأساسي للمشروع
# ----------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# ----------------------------------------
# 🔐 مفاتيح الأمان
# ----------------------------------------
SECRET_KEY = 'django-insecure-e%$c=9#24l3t59k5pmlgbz*50&*ap362_@u50e1ceb93*pwskz'

DEBUG = True
ALLOWED_HOSTS = []


# ----------------------------------------
# 🧩 التطبيقات المثبتة (Installed Apps)
# ----------------------------------------
INSTALLED_APPS = [
    # 🧱 تطبيقات Django الأساسية
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ☁️ مكتبة Cloudinary
    'cloudinary',
    'cloudinary_storage',

    # 🌸 تطبيقات المشروع الخاصة
    'account.apps.AccountConfig',      # إدارة المستخدمين والعملاء
    'shop.apps.ShopConfig',            # المتجر والمنتجات والطلبات
    'dashboard.apps.DashboardConfig',  # لوحة التحكم والإحصاءات
]


# ----------------------------------------
# ⚙️ مكونات الوسيطة (Middleware)
# ----------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ----------------------------------------
# 🔗 إعدادات المسارات العامة (URLs)
# ----------------------------------------
ROOT_URLCONF = 'gogo.urls'


# ----------------------------------------
# 🧱 إعدادات القوالب (Templates)
# ----------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 🧭 مجلد القوالب العام
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ----------------------------------------
# 🚀 إعدادات WSGI
# ----------------------------------------
WSGI_APPLICATION = 'gogo.wsgi.application'


# ----------------------------------------
# 🗃️ قاعدة البيانات
# ----------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ----------------------------------------
# 🔑 تحقق كلمات المرور
# ----------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ----------------------------------------
# 🌍 الإعدادات الإقليمية
# ----------------------------------------
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# ----------------------------------------
# 🎨 إعدادات الملفات الثابتة (Static)
# ----------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'


# ----------------------------------------
# ☁️ إعداد Cloudinary لتخزين ملفات الميديا
# ----------------------------------------
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


# ----------------------------------------
# 📸 إعدادات الوسائط (MEDIA)
# ----------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # فقط مرجعية احتياطية محلية


# ----------------------------------------
# 🧱 الإعداد الافتراضي للمفاتيح الأساسية للنماذج
# ----------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
