"""
Django settings for gogo project.

Generated by 'django-admin startproject' using Django 5.2.7.

Documentation:
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path
import os

# ----------------------------------------
# 📂 المسار الأساسي للمشروع
# ----------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# ----------------------------------------
# 🔐 مفاتيح الأمان
# ----------------------------------------
SECRET_KEY = 'django-insecure-e%$c=9#24l3t59k5pmlgbz*50&*ap362_@u50e1ceb93*pwskz'

# ⚠️ تفعيل وضع التطوير (يجب تعطيله في الإنتاج)
DEBUG = True

ALLOWED_HOSTS = []


# ----------------------------------------
# 🧩 التطبيقات المثبتة (Installed Apps)
# ----------------------------------------
INSTALLED_APPS = [
    # 🧱 تطبيقات Django الأساسية
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 🌸 تطبيقات المشروع الخاصة
    'account.apps.AccountConfig',      # إدارة المستخدمين والعملاء
    'shop.apps.ShopConfig',            # المتجر والمنتجات والطلبات
    'dashboard.apps.DashboardConfig',  # لوحة التحكم والإحصاءات
]


# ----------------------------------------
# ⚙️ مكونات الوسيطة (Middleware)
# ----------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # لتفعيل دعم اللغة
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ----------------------------------------
# 🔗 إعدادات المسارات العامة (URLs)
# ----------------------------------------
ROOT_URLCONF = 'gogo.urls'


# ----------------------------------------
# 🧱 إعدادات القوالب (Templates)
# ----------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # 🧭 مسار القوالب العام داخل المشروع
        'DIRS': [BASE_DIR / 'templates'],



        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ----------------------------------------
# 🚀 إعدادات WSGI (نقطة الدخول للتطبيق)
# ----------------------------------------
WSGI_APPLICATION = 'gogo.wsgi.application'


# ----------------------------------------
# 🗃️ قاعدة البيانات (SQLite مؤقتًا للتطوير)
# ----------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ----------------------------------------
# 🔑 تحقق كلمات المرور (Password Validation)
# ----------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ----------------------------------------
# 🌍 الإعدادات الإقليمية (اللغة والتوقيت)
# ----------------------------------------
LANGUAGE_CODE = 'ar'           # اللغة الافتراضية: العربية
TIME_ZONE = 'Asia/Riyadh'      # التوقيت المحلي: السعودية
USE_I18N = True
USE_L10N = True
USE_TZ = True


# ----------------------------------------
# 🎨 الملفات الثابتة والإعلامية (Static & Media)
# ----------------------------------------

# 🖼️ إعدادات الملفات الثابتة (CSS / JS / Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',           # ملفات التطوير (تُستخدم أثناء البرمجة)
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # ملفات الإنتاج (بعد أمر collectstatic)

# 📸 إعدادات ملفات الوسائط المرفوعة (من المستخدمين)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'         # موقع تخزين الصور والملفات المرفوعة


# ----------------------------------------
# 🧱 الإعداد الافتراضي للمفاتيح الأساسية للنماذج
# ----------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
