# Generated by Django 5.2.7 on 2025-10-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='نص التنبيه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة؟')),
            ],
            options={
                'verbose_name': 'تنبيه إداري',
                'verbose_name_plural': 'التنبيهات الإدارية',
            },
        ),
    ]
