# Generated by Django 5.2.7 on 2025-10-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'تنبيه إداري', 'verbose_name_plural': 'التنبيهات الإدارية'},
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='فعّل هذا الخيار إذا تمت قراءة التنبيه.', verbose_name='تمت القراءة؟'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='message',
            field=models.CharField(help_text='اكتب نص التنبيه الذي سيظهر في لوحة التحكم.', max_length=255, verbose_name='نص التنبيه'),
        ),
    ]
