# Generated by Django 5.2.7 on 2025-10-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='حمّل صورة المنتج (اختياري).', null=True, upload_to='products/', verbose_name='صورة المنتج'),
        ),
    ]
