# Generated by Django 5.2.7 on 2025-10-14 09:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='حمّل صورة المنتج (اختياري).', max_length=255, null=True, verbose_name='صورة المنتج'),
        ),
    ]
